spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: elchin@div.edu.az
    password: yyqhhzjetdctbesh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true